# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def Problem2 (n) :
    sum = 0
    fib1 = 1
    fib2 = 1
    fib = fib1 + fib2
    while fib <= n :
        if fib % 2 == 0 :
            sum += fib
        fib1 = fib2
        fib2 = fib

        fib = fib1 + fib2
    return sum

print (Problem2 (4000000))
