/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
 
public class Problem2 {

  public static void main(String[] args) {
  
    int fib1 = 1;
    int fib2 = 1;
    
    int fib = fib1 + fib2;
    int sum = 0;
    
    while (fib <= 4000000) {
      
      if (fib % 2 == 0) {
      
        sum += fib;
        System.out.print(fib + " ");
      }
      
      fib1 = fib2;
      fib2 = fib;
      
      fib = fib1 + fib2;
    }
    
    System.out.print(sum);
  }
}
